name = "jomao-group-join"
main = "src/index.js"
compatibility_date = "2026-10-09"

[vars]
FIREBASE_PROJECT_ID = "saving-app-da3b7"
FIREBASE_API_KEY = "AIzaSyDDGb1bNysz2Vszt116K2a3GGL9Rzsx9II"
APP_ORIGIN = "*"
